# GBDT学习

## 梯度提升正则

In [1]:
# 导入必要的包
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# 生成数据
from sklearn.datasets import make_hastie_10_2

X, y = make_hastie_10_2(n_samples=12000, random_state=1)

In [3]:
X

array([[ 1.62434536, -0.61175641, -0.52817175, ..., -0.7612069 ,
         0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , ..., -0.87785842,
         0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072, ..., -0.93576943,
        -0.26788808,  0.53035547],
       ...,
       [-0.93116013, -1.66204029,  0.30451552, ..., -0.13420095,
         0.29183149, -0.43300684],
       [-1.3787448 ,  0.83384136, -1.53900483, ...,  0.89981334,
        -1.44271785,  2.51028547],
       [ 0.82776805,  2.04855517,  2.77822335, ...,  0.12579842,
        -0.1916412 ,  0.67553921]])

In [4]:
X.astype(np.float32)

array([[ 1.6243454 , -0.6117564 , -0.5281718 , ..., -0.7612069 ,
         0.3190391 , -0.24937038],
       [ 1.4621079 , -2.0601406 , -0.3224172 , ..., -0.8778584 ,
         0.04221375,  0.58281523],
       [-1.1006192 ,  1.1447237 ,  0.9015907 , ..., -0.93576944,
        -0.26788807,  0.53035545],
       ...,
       [-0.93116015, -1.6620402 ,  0.3045155 , ..., -0.13420095,
         0.2918315 , -0.43300685],
       [-1.3787448 ,  0.8338414 , -1.5390048 , ...,  0.89981335,
        -1.4427178 ,  2.5102854 ],
       [ 0.827768  ,  2.0485551 ,  2.7782233 , ...,  0.12579842,
        -0.1916412 ,  0.6755392 ]], dtype=float32)

In [5]:
X.shape

(12000, 10)

In [6]:
y

array([ 1.,  1., -1., ..., -1.,  1.,  1.])

In [7]:
np.unique(y)

array([-1.,  1.])

In [8]:
labels, y = np.unique(y, return_inverse=True)

In [9]:
labels

array([-1.,  1.])

In [10]:
y

array([1, 1, 0, ..., 0, 1, 1], dtype=int64)

In [11]:
# 划分训练集和测试集
X_train = X[0:2000]
X_test = X[2000:]
y_train = y[0:2000]
y_test = y[2000:]

In [12]:
from sklearn import ensemble

original_params = {'n_estimators': 1000, 'max_leaf_nodes': 4, 'max_depth': None, 'random_state': 2,
                   'min_samples_split': 5}

plt.figure()

for label, color, setting in [('No shrinkage', 'orange',
                               {'learning_rate': 1.0, 'subsample': 1.0}),
                              ('learning_rate=0.1', 'turquoise',
                               {'learning_rate': 0.1, 'subsample': 1.0}),
                              ('subsample=0.5', 'blue',
                               {'learning_rate': 1.0, 'subsample': 0.5}),
                              ('learning_rate=0.1, subsample=0.5', 'gray',
                               {'learning_rate': 0.1, 'subsample': 0.5}),
                              ('learning_rate=0.1, max_features=2', 'magenta',
                               {'learning_rate': 0.1, 'max_features': 2})]:
    params = dict(original_params)
    params.update(setting)

    clf = ensemble.GradientBoostingClassifier(**params)
    clf.fit(X_train, y_train)

    # compute test set deviance
    test_deviance = np.zeros((params['n_estimators'],), dtype=np.float64)

    for i, y_pred in enumerate(clf.staged_decision_function(X_test)):
        # clf.loss_ assumes that y_test[i] in {0, 1}
        test_deviance[i] = clf.loss_(y_test, y_pred)

    plt.plot((np.arange(test_deviance.shape[0]) + 1)[::5], test_deviance[::5],
            '-', color=color, label=label)

plt.legend(loc='upper left')
plt.xlabel('Boosting Iterations')
plt.ylabel('Test Set Deviance')

plt.show()

AttributeError: 'GradientBoostingClassifier' object has no attribute 'loss_'

<Figure size 640x480 with 0 Axes>